# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        # first row
        self.inputLayout = QtWidgets.QHBoxLayout()
        self.inputLayout.setObjectName("inputLayout")
        self.SerialPortLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.SerialPortLabel.sizePolicy().hasHeightForWidth()
        )
        self.SerialPortLabel.setSizePolicy(sizePolicy)
        self.SerialPortLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SerialPortLabel.setObjectName("SerialPortLabel")
        self.inputLayout.addWidget(self.SerialPortLabel)
        self.SerialPortCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.SerialPortCombo.sizePolicy().hasHeightForWidth()
        )
        self.SerialPortCombo.setSizePolicy(sizePolicy)
        self.SerialPortCombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SerialPortCombo.setObjectName("SerialPortCombo")
        self.inputLayout.addWidget(self.SerialPortCombo)
        self.BaudRateLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.BaudRateLabel.sizePolicy().hasHeightForWidth()
        )
        self.BaudRateLabel.setSizePolicy(sizePolicy)
        self.BaudRateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BaudRateLabel.setObjectName("BaudRateLabel")
        self.inputLayout.addWidget(self.BaudRateLabel)
        self.BaudRateCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.BaudRateCombo.sizePolicy().hasHeightForWidth()
        )
        self.BaudRateCombo.setSizePolicy(sizePolicy)
        self.BaudRateCombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BaudRateCombo.setObjectName("BaudRateCombo")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.BaudRateCombo.addItem("")
        self.inputLayout.addWidget(self.BaudRateCombo)
        # self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        # sizePolicy.setHorizontalStretch(5)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.outputLabel.sizePolicy().hasHeightForWidth())
        # self.outputLabel.setSizePolicy(sizePolicy)
        # self.outputLabel.setAlignment(QtCore.Qt.AlignCenter)
        # self.outputLabel.setObjectName("outputLabel")
        # self.inputLayout.addWidget(self.outputLabel)
        # self.outputCombo = QtWidgets.QComboBox(self.centralwidget)
        # self.outputCombo.setEnabled(False)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(5)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.outputCombo.sizePolicy().hasHeightForWidth())
        # self.outputCombo.setSizePolicy(sizePolicy)
        # self.outputCombo.setObjectName("outputCombo")
        # self.outputCombo.addItem("")
        # self.outputCombo.addItem("")
        # self.outputCombo.addItem("")
        # self.inputLayout.addWidget(self.outputCombo)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setEnabled(True)
        self.connectButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.connectButton.setObjectName("connectButton")
        self.connectButton.setSizePolicy(sizePolicy)
        self.inputLayout.addWidget(self.connectButton)

        self.seperatorLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.seperatorLabel.sizePolicy().hasHeightForWidth()
        )
        self.seperatorLabel.setSizePolicy(sizePolicy)
        self.seperatorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.seperatorLabel.setObjectName("seperatorLabel")
        self.inputLayout.addWidget(self.seperatorLabel)
        self.seperatorLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.seperatorLineEdit.sizePolicy().hasHeightForWidth()
        )
        self.seperatorLineEdit.setSizePolicy(sizePolicy)
        self.seperatorLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.seperatorLineEdit.setObjectName("seperatorLineEdit")
        self.inputLayout.addWidget(self.seperatorLineEdit)
        self.verticalLayout.addLayout(self.inputLayout)
        # second row
        self.data_layer = QtWidgets.QHBoxLayout()
        self.data_layer.setObjectName("buttonLayout")

        self.csvButton = QtWidgets.QPushButton(self.centralwidget)
        self.csvButton.setEnabled(True)
        self.csvButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.csvButton.setObjectName("Choose CSV")
        self.data_layer.addWidget(self.csvButton)

        self.csvLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        # sizePolicy.setHorizontalStretch(1)
        # sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csvLabel.sizePolicy().hasHeightForWidth())
        self.csvLabel.setAlignment(QtCore.Qt.AlignCenter)
        sizePolicy.setHorizontalStretch(6)
        self.csvLabel.setSizePolicy(sizePolicy)
        self.csvLabel.setObjectName("csvLabel")
        self.data_layer.addWidget(self.csvLabel)

        self.recorderCombo = QtWidgets.QComboBox(self.centralwidget)
        self.recorderCombo.setEnabled(True)
        self.recorderCombo.setObjectName("recorderCombo")
        self.recorderCombo.addItem("")
        self.recorderCombo.addItem("")
        self.recorderCombo.addItem("")
        self.recorderCombo.addItem("")
        self.recorderCombo.addItem("")
        sizePolicy.setHeightForWidth(
            self.recorderCombo.sizePolicy().hasHeightForWidth()
        )
        sizePolicy.setHorizontalStretch(2)
        self.recorderCombo.setSizePolicy(sizePolicy)
        self.recorderCombo.setObjectName("csvLabel")
        self.data_layer.addWidget(self.recorderCombo)

        self.verticalLayout.addLayout(self.data_layer)

        # third row
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")

        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.buttonLayout.addWidget(self.timeLabel)

        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setEnabled(False)
        self.startButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startButton.setObjectName("startButton")
        self.buttonLayout.addWidget(self.startButton)

        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopButton.setObjectName("stopButton")
        self.buttonLayout.addWidget(self.stopButton)

        self.putSepButton = QtWidgets.QPushButton(self.centralwidget)
        self.putSepButton.setEnabled(False)
        self.putSepButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.putSepButton.setObjectName("putSepButton")
        self.buttonLayout.addWidget(self.putSepButton)

        # self.labelLabel = QtWidgets.QLabel(self.centralwidget)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        # sizePolicy.setHorizontalStretch(1)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.labelLabel.sizePolicy().hasHeightForWidth())
        # self.labelLabel.setSizePolicy(sizePolicy)
        # self.labelLabel.setObjectName("labelLabel")
        # self.buttonLayout.addWidget(self.labelLabel)

        # self.labelLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(10)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.labelLineEdit.sizePolicy().hasHeightForWidth())
        # self.labelLineEdit.setSizePolicy(sizePolicy)
        # self.labelLineEdit.setFrame(True)
        # self.labelLineEdit.setClearButtonEnabled(False)
        # self.labelLineEdit.setObjectName("labelLineEdit")
        # self.buttonLayout.addWidget(self.labelLineEdit)

        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.textEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SerialPortLabel.setText(_translate("MainWindow", "Serial Port"))
        self.BaudRateLabel.setText(_translate("MainWindow", "Baud Rate"))
        # self.BaudRateCombo.setItemText(0, _translate("MainWindow", "300 baud"))
        # self.BaudRateCombo.setItemText(1, _translate("MainWindow", "1200 baud"))
        # self.BaudRateCombo.setItemText(2, _translate("MainWindow", "2400 baud"))
        # self.BaudRateCombo.setItemText(3, _translate("MainWindow", "4800 baud"))
        self.BaudRateCombo.setItemText(4, _translate("MainWindow", "9600 baud"))
        # self.BaudRateCombo.setItemText(5, _translate("MainWindow", "19200 baud"))
        # self.BaudRateCombo.setItemText(6, _translate("MainWindow", "38400 baud"))
        # self.BaudRateCombo.setItemText(7, _translate("MainWindow", "57600 baud"))
        # self.BaudRateCombo.setItemText(8, _translate("MainWindow", "74880 baud"))
        # self.BaudRateCombo.setItemText(9, _translate("MainWindow", "115200 baud"))
        # self.BaudRateCombo.setItemText(10, _translate("MainWindow", "230400 baud"))
        # self.BaudRateCombo.setItemText(11, _translate("MainWindow", "250000 baud"))
        # self.BaudRateCombo.setItemText(12, _translate("MainWindow", "500000 baud"))
        # self.BaudRateCombo.setItemText(13, _translate("MainWindow", "1000000 baud"))
        # self.BaudRateCombo.setItemText(14, _translate("MainWindow", "2000000 baud"))
        # self.outputLabel.setText(_translate("MainWindow", "Output"))
        # self.outputCombo.setItemText(0, _translate("MainWindow", "pkl"))
        # self.outputCombo.setItemText(1, _translate("MainWindow", "csv"))
        # self.outputCombo.setItemText(2, _translate("MainWindow", "txt"))
        self.recorderCombo.setItemText(0, _translate("MainWindow", "salman"))
        self.recorderCombo.setItemText(1, _translate("MainWindow", "rajab"))
        self.recorderCombo.setItemText(2, _translate("MainWindow", "tarab"))
        self.recorderCombo.setItemText(3, _translate("MainWindow", "fada"))
        self.recorderCombo.setItemText(4, _translate("MainWindow", "negin"))

        self.seperatorLabel.setText(_translate("MainWindow", "Seperator"))
        self.seperatorLineEdit.setText(_translate("MainWindow", ";"))
        self.csvButton.setText(_translate("MainWindow", "Choose CSV"))
        self.csvLabel.setText(
            _translate("MainWindow", "Choose CSV file to show the next label.")
        )
        self.csvLabel.setStyleSheet(
            "border: 1px solid white; border-radius: 10px; padding: 5px 5px;"
        )
        self.timeLabel.setText(_translate("MainWindow", "Record Time: 00:00"))
        self.startButton.setText(_translate("MainWindow", "Start Recording"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.stopButton.setText(_translate("MainWindow", "Stop Recording"))
        self.putSepButton.setText(_translate("MainWindow", "Put Seperator"))
        # self.labelLabel.setText(_translate("MainWindow", "Label"))
        self.saveButton.setText(_translate("MainWindow", "Save Data"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
